### PR TITLE
Check that push certificate contains UID with required prefix

### LINKED ISSUE #367: Validation of push certificate on mdm startup
It's possible to run _micromdm serve -apns-cert cert_and_key.p12_ even though the p12 file contains a certificate that is not a push certificate. If the wrong type of certificate is used an iOS client will reject the enrollment profile.

It would be helpful for the user if the micromdm refuse to start unless the certificate is a "push certificate". 

Issue #366 shows the result of starting the mdm with a vendor certificate (aka CSR certificate) instead of a signed push certificate.

### PR DESCRIPTION
**Pull request by larsar**
Checks if the subject field of the push certificate contains the required prefix. Unless it does, it's probably not a push certificate. 

This issue fixes #367.
Initially I started micromdm using a "csr certificate" from Apple (ref #366). I tested the same scenario after extending the cert validation, and the server aborted as expected.

```
ts="2018/01/25 10:59:08" msg="enrollment service: get apns topic from certificate: invalid Push Topic (UserID OID) in certificate. Must start with 'com.apple.mgmt', was: 95PAURT649"
```

### CODE REVIEW

File: pkg/crypto/helpers.go [hunk 1]
```diff
@@ -121,7 +122,12 @@ func TopicFromCert(cert *x509.Certificate) (string, error) {
 	var oidASN1UserID = asn1.ObjectIdentifier{0, 9, 2342, 19200300, 100, 1, 1}
 	for _, v := range cert.Subject.Names {
 		if v.Type.Equal(oidASN1UserID) {
-			return v.Value.(string), nil
+			var uid = v.Value.(string)
+			if strings.HasPrefix(uid, "com.apple.mgmt") {
+				return v.Value.(string), nil
+			} else {
```
Comment (groob) [inline pkg/crypto/helpers.go]: there's no need for an `else` branch if you have a return.

File: pkg/crypto/helpers.go [hunk 2]
```diff
@@ -121,7 +122,12 @@ func TopicFromCert(cert *x509.Certificate) (string, error) {
 	var oidASN1UserID = asn1.ObjectIdentifier{0, 9, 2342, 19200300, 100, 1, 1}
 	for _, v := range cert.Subject.Names {
 		if v.Type.Equal(oidASN1UserID) {
-			return v.Value.(string), nil
+			var uid = v.Value.(string)
```
Comment (groob) [inline pkg/crypto/helpers.go]: this will panic if value is not a string. Unlikely but might be worth checking. 

https://golang.org/doc/effective_go.html#interface_conversions
```
str, ok := value.(string)
if ok {
    fmt.Printf("string value is: %q\n", str)
} else {
    fmt.Printf("value is not a string\n")
}
```

File: pkg/crypto/helpers.go [hunk 3]
```diff
@@ -121,7 +122,12 @@ func TopicFromCert(cert *x509.Certificate) (string, error) {
...
+			if strings.HasPrefix(uid, "com.apple.mgmt") {
+				return v.Value.(string), nil
```
Comment (groob) [inline pkg/crypto/helpers.go]: `uid` already has the cast value.

File: pkg/crypto/helpers_test.go [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+
+func TestTopicFromCertWithWrongUidPrefix(t *testing.T) {
+	expectPushCertError("testdata/mock_push_cert_wrong_uid_prefix.pem", t)
+}
+
+func TestTopicFromCertWithoutUid(t *testing.T) {
+	expectPushCertError("testdata/mock_push_cert_no_uid.pem", t)
+}
+
+func expectPushCertError(certPath string, t *testing.T) {
```
Comment (groob) [inline pkg/crypto/helpers_test.go]: helpers should have `t.Testing` as the first argument. let's reverse this order.

File: pkg/crypto/helpers_test.go [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+func TestTopicFromValidCert(t *testing.T) {
+	certificate, _ := ReadPEMCertificateFile("testdata/mock_push_cert.pem")
+	pushTopic, err := TopicFromCert(certificate)
+
+	if err != nil {
+		t.Errorf("fail %s", err)
+	}
+
+	if have, want := pushTopic, "com.apple.mgmt.External.18a16429-886b-41f1-9c30-2bd04ae4fc37"; have != want {
+		t.Errorf("have %d, want %d", have, want)
```
Comment (groob) [inline pkg/crypto/helpers_test.go]: %d is for integers. This should be a `%s`

File: pkg/crypto/helpers_test.go [hunk 6]
```diff
@@ -0,0 +1,35 @@
+package crypto
+
+import (
+	"testing"
+)
+
+func TestTopicFromValidCert(t *testing.T) {
+	certificate, _ := ReadPEMCertificateFile("testdata/mock_push_cert.pem")
+	pushTopic, err := TopicFromCert(certificate)
+
```
Comment (groob) [inline pkg/crypto/helpers_test.go]: remove the extra line. `if err != nil` should be grouped with the TopicFromCert call.

File: pkg/crypto/helpers_test.go [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+	if err != nil {
+		t.Errorf("fail %s", err)
```
Comment (groob) [inline pkg/crypto/helpers_test.go]: You can use `t.Fatalf` here to stop the test execution if an error was returned. 
In case of `pushTopic` it doesn't matter too much because it's a string with a default value of `""`, but if you had a function which returned a pointer, the default value would be nil, likely causing a panic if the test continued. 

https://golang.org/pkg/testing/#T.Fatalf

File: pkg/crypto/helpers_test.go [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+	}
+
+	if have, want := pushTopic, "com.apple.mgmt.External.18a16429-886b-41f1-9c30-2bd04ae4fc37"; have != want {
+		t.Errorf("have %d, want %d", have, want)
+	}
+}
+
+func TestTopicFromCertWithWrongUidPrefix(t *testing.T) {
```
Comment (groob) [inline pkg/crypto/helpers_test.go]: IMO these tests are a bit too short. A common go pattern is to write a [table test](https://github.com/golang/go/wiki/TableDrivenTests).

[Subtests](https://blog.golang.org/subtests) also help a lot when working with a table test. 

And here's an example in the wild. https://github.com/oklog/oklog/blob/7fa04d3c21f8fedb54940c069c02e450c7cc8eb3/pkg/store/overlap_test.go

**Comment by larsar** [comment]
Thanks for the thorough review, @groob. It's great way to learn! :)

File: pkg/crypto/helpers.go (hunk 1 above)
Comment (larsar) [reply pkg/crypto/helpers.go]: I'm not sure I understand you correctly on this one. If no UID is found, the function returns an error. If the UID is present, then the code will check if it has the required prefix or not. In either case it should break the loop, which the return does, but in one case it should return the UID value, in the other case it should return an error. 

If I remove the else block the method will return the error message at the bottom of the method instead a more explanatory error message defined in the else block.

File: pkg/crypto/helpers_test.go (hunk 6 above)
Comment (larsar) [reply pkg/crypto/helpers_test.go]: Like this?
```
	if pushTopic, err := TopicFromCert(certificate); err != nil {
		t.Errorf("fail %s", err)
	} else {
		if have, want := pushTopic, "com.apple.mgmt.External.18a16429-886b-41f1-9c30-2bd04ae4fc37"; have != want {
			t.Errorf("have %d, want %d", have, want)
		}
	}
```

Not sure I like to nest the next test inside an else block, but the pushTopic variable will be scoped to the if block if do it like this.

Sorry for my n00b Go knowledge. I watched a Go crash course on high speed before starting coding. :)

File: pkg/crypto/helpers_test.go (hunk 5 above)
Comment (larsar) [reply pkg/crypto/helpers_test.go]: Doh.... Last minute refactoring with some copy/paste. :)

File: pkg/crypto/helpers.go (hunk 2 above)
Comment (larsar) [reply pkg/crypto/helpers.go]: Wilco

File: pkg/crypto/helpers_test.go (hunk 7 above)
Comment (larsar) [reply pkg/crypto/helpers_test.go]: I agree. Fatal it is. :)

File: pkg/crypto/helpers_test.go (hunk 4 above)
Comment (larsar) [reply pkg/crypto/helpers_test.go]: Wilco

File: pkg/crypto/helpers_test.go (hunk 8 above)
Comment (larsar) [reply pkg/crypto/helpers_test.go]: I'll check out the table test patterns. I agree that a whole function for "one liner tests" is not ideal.

File: pkg/crypto/helpers_test.go (hunk 6 above)
Comment (groob) [reply pkg/crypto/helpers_test.go]: Sorry what I meant by this comment is to remove the newline between TopicFromCert and the `if err != nil` (line 10)

The actual code is fine.

File: pkg/crypto/helpers.go (hunk 1 above)
Comment (groob) [reply pkg/crypto/helpers.go]: > If no UID is found, the function returns an error

and function execution stops because the error was returned. The behavior is the same wether `else` is present or not. 
All I'm advocating for is to remove the extra branch and keep the code from within the `else` statement at a different indentation level. 

This comment would also come from `golint` I believe. 

Take this example: 
```
func get(i int) int {
    if f := i * 2; f == 6 {
        return f
    } else {
        return f * 3
    }
}
``` 

The code is correct, but the recommended go style is to write it like this:

```
func get(i int) int {
    f := i * 2
    if f == 6 {
        return f
    }
    return f * 3
}
```

**Comment by larsar** [comment]
Squashed and pushed now. :)
