### PR TITLE
Clear a UDID's command queue during Authenticate Check-in (enrollment)

### LINKED ISSUE #647: Clear command queue when a device is deleted
# What version of `micromdm` are you using?
1.6.0

When a device is removed from micromdm, any existing commands are not cleared from the queue. This can resulting in unexpected behavior when the device is reenrolled in the future. 

When a device is removed from micromdm, scrub any entries related to that device from the command queue. Future Tim thanks you.

### PR DESCRIPTION
**Pull request by jessepeterson**
Fixes #647 and addresses the mentioned symptom in #646.

### CODE REVIEW

File: mdm/checkin.go [hunk 1]
```diff
@@ -27,6 +27,13 @@ func (svc *MDMService) Checkin(ctx context.Context, event CheckinEvent) error {
 		return errors.Wrap(err, "get checkin topic from message")
 	}
 
+	if topic == AuthenticateTopic {
```
Comment (groob) [inline mdm/checkin.go:30]: Probably doesn't make much of a difference, but `TokenUpdate` is when you really know if an enrollment happened.

File: mdm/checkin.go [hunk 2]
```diff
@@ -27,6 +27,13 @@ func (svc *MDMService) Checkin(ctx context.Context, event CheckinEvent) error {
...
+		err = svc.queue.Clear(ctx, event)
```
Comment (groob) [inline mdm/checkin.go:31]: prefer `if err := `

File: platform/queue/queue.go [hunk 3]
```diff
@@ -54,6 +54,34 @@ func (db *Store) Next(ctx context.Context, resp mdm.Response) ([]byte, error) {
...
+	udid := event.Command.UDID
+	if event.Command.UserID != "" {
+		udid = event.Command.UserID
+	}
+	if event.Command.EnrollmentID != "" {
+		udid = event.Command.EnrollmentID
+	}
+
+	dc, err := db.DeviceCommand(udid)
+	if err != nil {
```
Comment (groob) [inline platform/queue/queue.go:67]:
```
if isNotFound { return nil }
else if err != nil { // wrap and return }
```

File: platform/queue/queue.go [hunk 4]
```diff
@@ -54,6 +54,34 @@ func (db *Store) Next(ctx context.Context, resp mdm.Response) ([]byte, error) {
...
+		if isNotFound(err) {
+			return nil
+		}
+		return errors.Wrapf(err, "get device command from queue, udid: %s", udid)
```
Comment (groob) [inline platform/queue/queue.go:71]: Maybe `get device to clear queue`?

File: platform/queue/queue.go [hunk 5]
```diff
@@ -54,6 +54,34 @@ func (db *Store) Next(ctx context.Context, resp mdm.Response) ([]byte, error) {
...
+	}
+
+	dc.Commands = nil
+	dc.NotNow = nil
+
+	err = db.Save(dc)
+	if err != nil {
+		return err
```
Comment (groob) [inline platform/queue/queue.go:79]: either wrap, or `return db.Save(dc)`

File: mdm/checkin.go (hunk 1 above)
Comment (jessepeterson) [reply mdm/checkin.go:30]: This is true. However since this service doesn't know which `TokenUpdate` has happened (the first, or any subsequent) it could potentially clear the queue in the midst of normal MDM operation if we checked on token update. `Authenticate` only happens during initial enrollment.

Separately I considered clearing on a `Checkout` event but decided against it for forensics considerations. Also separately I considered appending the queued commands to the "Failed" queue for forensics but decided that'd be far-fetched.
